    timer0 u_timer0(.rst_n_i(rst_n_i),
        .clk_i(clk_i),
        .apb_psel_i(apb_psel_i),
        .apb_paddr_i(apb_paddr_i),
        .apb_pwdata_i(apb_pwdata_i),
        .apb_pwrite_i(apb_pwrite_i),
        .apb_penable_i(apb_penable_i),
        .apb_pready_o(apb_pready_o),
        .apb_prdata_o(apb_prdata_o),
        .apb_pslverr_o(apb_pslverr_o),
        .int_o(int_o),
        .timeout_o(timeout_o));
