/*******************************************************************************
    Verilog netlist generated by IPGEN Lattice Propel (64-bit)
    2022.1.2209140739
    Soft IP Version: 1.7.0
    2022 09 14 16:29:24
*******************************************************************************/
/*******************************************************************************
    Wrapper Module generated per user settings.
*******************************************************************************/
module pll0 (clki_i, rstn_i, clkop_o, clkos_o, lock_o)/* synthesis syn_black_box syn_declare_black_box=1 */;
    input  clki_i;
    input  rstn_i;
    output  clkop_o;
    output  clkos_o;
    output  lock_o;
endmodule