/*******************************************************************************
    Verilog netlist generated by IPGEN Lattice Propel (64-bit)
    2023.2.2311232310
    Soft IP Version: 1.3.0
    2024 06 21 20:41:03
*******************************************************************************/
/*******************************************************************************
    Wrapper Module generated per user settings.
*******************************************************************************/
module timer0 (rst_n_i, clk_i, apb_psel_i, apb_paddr_i, apb_pwdata_i,
    apb_pwrite_i, apb_penable_i, apb_pready_o, apb_prdata_o, apb_pslverr_o,
    int_o, timeout_o)/* synthesis syn_black_box syn_declare_black_box=1 */;
    input  rst_n_i;
    input  clk_i;
    input  apb_psel_i;
    input  [31:0]  apb_paddr_i;
    input  [31:0]  apb_pwdata_i;
    input  apb_pwrite_i;
    input  apb_penable_i;
    output  apb_pready_o;
    output  [31:0]  apb_prdata_o;
    output  apb_pslverr_o;
    output  int_o;
    output  [3:0]  timeout_o;
endmodule