/*******************************************************************************
    Verilog netlist generated by IPGEN Lattice Propel (64-bit)
    2023.2.2311232310
    Soft IP Version: 2.0.1
    2024 06 25 15:41:10
*******************************************************************************/
/*******************************************************************************
    Wrapper Module generated per user settings.
*******************************************************************************/
module i2c0 (scl_io, sda_io, clk_i, rst_n_i, int_o, apb_penable_i, apb_psel_i,
    apb_pwrite_i, apb_paddr_i, apb_pwdata_i, apb_pready_o, apb_pslverr_o,
    apb_prdata_o)/* synthesis syn_black_box syn_declare_black_box=1 */;
    inout  scl_io;
    inout  sda_io;
    input  clk_i;
    input  rst_n_i;
    output  int_o;
    input  apb_penable_i;
    input  apb_psel_i;
    input  apb_pwrite_i;
    input  [5:0]  apb_paddr_i;
    input  [31:0]  apb_pwdata_i;
    output  apb_pready_o;
    output  apb_pslverr_o;
    output  [31:0]  apb_prdata_o;
endmodule